name: Test Build

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test-build.yml"
  pull_request:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install modules
        run: pnpm install --no-frozen-lockfile

      - name: Prepare project
        run: pnpm dev:prepare

      - name: Build module
        run: pnpm prepack
